In [23]:
import pandas as pd
import torch
from sqlalchemy import create_engine, text
from admin import POSTGRES_PASS, DB_USER, DB_PASSWORD, DB_HOST
from alpaca_api import get_news
from datasets import load_dataset
from transformers import pipeline, AutoModel, AutoTokenizer
# from peft import PeftModel
import matplotlib.pyplot as plt

In [24]:
DB_MODE = "local"
device = "cuda" if torch.cuda.is_available() else "cpu"

In [25]:
def fetch_database(DB_MODE="container"):
    if DB_MODE == "local":
        connection = f'postgresql+psycopg2://postgres:{POSTGRES_PASS}@localhost:5432/stock_market'
    elif DB_MODE == "cloud":
        connection = f'postgresql://{DB_USER}:{DB_PASSWORD}@{DB_HOST}:5432/postgres' 
    elif DB_MODE =="container":
        stocks_df = pd.read_parquet("stocks_data.parquet")
        futures_df = pd.read_parquet("futures_data.parquet")
        return stocks_df, futures_df
    else:
        raise ValueError(f"Invalid DB_MODE: '{DB_MODE}'. Use 'local', 'cloud', or 'container'.")

    db_engine = create_engine(connection)
    query = "SELECT * FROM stock_prices;"
    query2 = "SELECT * FROM futures_prices;"
        
    with db_engine.connect() as conn:
        stocks_result = conn.execute(text(query))
        futures_result = conn.execute(text(query2))
        
        stocks_rows = stocks_result.fetchall()
        stocks_column = stocks_result.keys()
    
        futures_rows = futures_result.fetchall()
        futures_column = futures_result.keys()        
    
    stocks_df = pd.DataFrame(stocks_rows, columns=stocks_column)
    futures_df = pd.DataFrame(futures_rows, columns=futures_column)
    
    return stocks_df, futures_df

In [26]:
stocks_df, futures_df = fetch_database(DB_MODE)

In [27]:
pd.set_option('display.max_colwidth', None)

In [28]:
stocks_df.tail()

stocks_df["ticker"].value_counts()

ticker
MSFT     8579
TSLA     8579
AMZN     8579
NVDA     8578
QQQ      8578
GOOGL    8577
AAPL     8577
META     8577
SPY      8575
Name: count, dtype: int64

In [29]:
futures_df.head()

futures_df["ticker"].value_counts()

ticker
GC=F    30451
CL=F    30240
SI=F    29592
Name: count, dtype: int64

In [32]:
def check_data_present(df):
    daily_counts = df.groupby(df["Datetime"].dt.date).size()

    EXPECTED_COUNT = 390 
    incomplete_days = daily_counts[daily_counts < EXPECTED_COUNT]
    
    if not incomplete_days.empty:
        print("Missing data detected on the following dates:")
        return incomplete_days
    else:
        return "All days appear to have complete data."

check_data_present(stocks_df)
check_data_present(futures_df)

Missing data detected on the following dates:

Datetime
2026-02-15     97
2026-02-22    150
2026-03-01    150
2026-03-08    331
2026-03-15    327
dtype: int64

In [38]:
sunday_starts = futures_df[futures_df['Datetime'].dt.dayofweek == 6].groupby(futures_df['Datetime'].dt.date)['Datetime'].min()
print(sunday_starts)

Datetime
2026-02-15   2026-02-15 23:22:00+00:00
2026-02-22   2026-02-22 23:10:00+00:00
2026-03-01   2026-03-01 23:10:00+00:00
2026-03-08   2026-03-08 22:09:00+00:00
2026-03-15   2026-03-15 22:10:00+00:00
Name: Datetime, dtype: datetime64[ns, UTC]

In [10]:
news_df = get_news("NVDA", "2026-03-02", desired_timeframe_in_days=3)
news_df.head()

,id,author,publish_time,headline,source,related_tickers,summary
0,51045029,The Arora Report,2026-03-04 18:15:16+00:00,Secret Iran Outreach And Trump's Promise Of Safe Shipping Saves Stock Market But Here's A Fly In The Ointment,benzinga,"[AAPL, AMZN, BTCUSD, EWY, GDX, GLD, GOOG, META, MSFT, NVDA, QQQ, SIL, SLV, SPY, TSLA, USO]",\n\n\n\nSecret Iran Outreach\n\n\n
1,51043378,Benzinga Insights,2026-03-04 17:35:12+00:00,10 Information Technology Stocks Whale Activity In Today's Session,benzinga,"[ADBE, AMD, ASML, AVGO, CRWD, INTC, MU, NVDA, PANW, PLTR]",
2,51038396,Daragh Thomas,2026-03-04 15:39:22+00:00,Broadcom Earnings Prediction Market Preview: Can Hock Tan Succeed Where Jensen Huang Failed?,benzinga,"[AMD, AVGO, GOOGL, META, NVDA]","Broadcom (AVGO) has beaten EPS estimates for 19 straight quarters, but NVIDIA&#39;s (NVDA) recent beat and drop raises questions on the importance of beating estimates."
3,51036108,Anusuya Lahiri,2026-03-04 15:00:28+00:00,"Nvidia Leads Chip Stock Rebound, Billionaire Investor Buys 1 Million Shares To Defy AI 'Bubble' Fears",benzinga,"[AMD, ARM, AVGO, INTC, MU, NVDA, ON, SMCI, SSNLF, STX, TSLA, TSM, WDC]",Semiconductor stocks like Nvidia (NVDA) and AMD are bouncing back Wednesday. Discover why billionaire Leo KoGuan is doubling down on AI with a massive share purchase and why experts say the recent sell-off was a &#34;nervous market&#34; overreaction.
4,51028040,Eva Mathew,2026-03-04 13:55:49+00:00,"Stock Market Today: S&P 500, Dow Futures Up As Oil Prices Fall For First Time Since Iran War Began— Broadcom, Abercrombie & Fitch In Focus (UPDATED)",benzinga,"[ANF, AVGO, BOX, BTCUSD, CRWD, NVDA, OKTA, QQQ, ROST, SPY]","(Editor’s note: The headline, lede, and prices of futures, commodities, ETFs and stocks were updated and the ADP February jobs data was added)"

# FinBERT

In [11]:
class FinbertSentiment:
    def __init__(self):
        device = "cuda" if torch.cuda.is_available() else "cpu"
        self.pipe = pipeline(
            "sentiment-analysis", model="ProsusAI/finbert", device = device)

    def calc_sentiment_score(self, df, col):
        news_data = df[col].to_list()        
        sentiment = self.pipe(news_data, batch_size=32) 

        temp_df = pd.json_normalize(sentiment).rename(columns={
        'label': f'{col}_predicted_label',
        'score': f'{col}_probability_score'
    })
        df = pd.concat([df, temp_df], axis=1)
        
        return df

In [12]:
model = FinbertSentiment()

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
Loading weights: 100%|██████████| 201/201 [00:00<00:00, 15473.44it/s]
BertForSequenceClassification LOAD REPORT from: ProsusAI/finbert
Key                          | Status     |  |
-----------------------------+------------+--+-
bert.embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

## Financial Phrase Bank

In [13]:
fpb_data = [] # FinancialPhraseBank

with open("Sentences_75Agree.txt", "r", encoding="latin-1") as f:
    for line in f:
        sentence = line.strip().split('@')
        headline, label = sentence[0], sentence[1]
        fpb_data.append({
            "headline": headline,
            "true_label": label
        })

In [14]:
fpb_df = pd.DataFrame(fpb_data)

In [15]:
fpb_sentiment = model.calc_sentiment_score(fpb_df, "headline")

In [16]:
correct_pred = fpb_sentiment[fpb_sentiment["true_label"].values == fpb_sentiment["headline_predicted_label"].values]
accuracy =  len(correct_pred)/ len(fpb_sentiment)
print("---Financial Phrase Bank---\n")
print(f"finBERT accuracy: {accuracy*100:.2f}%")

---Financial Phrase Bank---

finBERT accuracy: 94.73%

## FiQA

In [17]:
fiqa_df = pd.read_csv('fiqa_train.csv')
fiqa_df.head(1)

,_id,sentence,target,aspect,score,type
0,1,Royal Mail chairman Donald Brydon set to step down,Royal Mail,Corporate/Appointment,-0.374,headline

In [18]:
def rough_score_to_label(score):
    if score < -0.1:
        return "negative"
    elif score > 0.1:
        return "positive"
    else:
        return "neutral"

fiqa_df["rough_true_label"] = fiqa_df["score"].apply(rough_score_to_label)

In [19]:
fiqa_sentiment = model.calc_sentiment_score(fiqa_df, "sentence")

In [20]:
fiqa_sentiment.head(1)

,_id,sentence,target,aspect,score,type,rough_true_label,sentence_predicted_label,sentence_probability_score
0,1,Royal Mail chairman Donald Brydon set to step down,Royal Mail,Corporate/Appointment,-0.374,headline,negative,neutral,0.70466

In [21]:
correct_pred = fiqa_sentiment[fiqa_sentiment["rough_true_label"].values == fiqa_sentiment["sentence_predicted_label"].values]
accuracy =  len(correct_pred)/ len(fiqa_sentiment)
print("---FiQa dataset---\n")
print(f"finBERT accuracy: {accuracy*100:.2f}%")
print("-"*30)

---FiQa dataset---

finBERT accuracy: 48.78%
------------------------------

## Twitter financial news sentiment dataset

In [22]:
def get_tfns():    
    tfns = load_dataset("zeroshot/twitter-financial-news-sentiment")
    df = tfns['train'].to_pandas()
    label_map = {0: "negative", 1: "positive", 2: "neutral"}
    df['label'] = df['label'].map(label_map)
    return df

In [23]:
tfns_df = get_tfns()

In [24]:
tfns_df.head(1)

,text,label
0,$BYND - JPMorgan reels in expectations on Beyond Meat https://t.co/bd0xbFGjkT,negative

In [25]:
tfns_sentiment = model.calc_sentiment_score(tfns_df, "text")

In [26]:
tfns_sentiment.head(1)

,text,label,text_predicted_label,text_probability_score
0,$BYND - JPMorgan reels in expectations on Beyond Meat https://t.co/bd0xbFGjkT,negative,negative,0.712802

In [27]:
correct_pred = tfns_sentiment[tfns_sentiment["label"].values == tfns_sentiment["text_predicted_label"].values]
accuracy =  len(correct_pred)/ len(tfns_sentiment)
print("---Twitter Financial News dataset---\n")
print(f"finBERT accuracy: {accuracy*100:.2f}%")
print("-"*30)

---Twitter Financial News dataset---

finBERT accuracy: 71.21%
------------------------------